/// Flutter icons MyIcons2
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyIcons2
///      fonts:
///       - asset: fonts/MyIcons2.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Maki, Copyright (C) Mapbox, LCC
///         Author:    Mapbox
///         License:   BSD (https://github.com/mapbox/maki/blob/gh-pages/LICENSE.txt)
///         Homepage:  http://mapbox.com/maki/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class MyIcons2 {
  MyIcons2();

  static const _kFontFam = 'MyIcons2';
  static const _kFontPkg = null;

  static const IconData add_a_photo = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_location = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData my_location = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location_off = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location_disabled = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit_location = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location_on = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData find_replace = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData place = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData local_airport = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData airport_shuttle = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData restaurant = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData restaurant_menu = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hotel = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData local_hospital = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData goat = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gavel = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData landscape = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData layers = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData local_convenience_store = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData local_car_wash = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData local_cafe = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData local_bar = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData local_gas_station = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData local_grocery_store = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData local_laundry_service = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData local_library = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData local_mall = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData local_pharmacy = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData local_post_office = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData harbor = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData local_taxi = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData local_shipping = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData motorcycle = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nature = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nature_people = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pets = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person_add = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData perm_device_information = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rowing = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData remove_circle = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData highlight_off = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData face = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData religious_christian = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData religious_islam = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData religious_jewish = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData error = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData directions_boat = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData directions_bike = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData directions_bus = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData directions_car = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData directions_railway = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData directions_run = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData directions_walk = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_circle = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData create = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData control_point = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_circle = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData h_sigh = IconData(0xf0fd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bank = IconData(0xf19c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hospital_alt = IconData(0xf47d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData church = IconData(0xf51d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hotel_1 = IconData(0xf594, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mosque = IconData(0xf678, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData place_of_worship = IconData(0xf67f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pray = IconData(0xf683, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData praying_hands = IconData(0xf684, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
